# Generated by Django 5.1.15 on 2026-09-23 16:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(default='विश्वगुरु (Vishwaguru)', max_length=150, verbose_name='समाचार पत्र का नाम / Newspaper Name')),
                ('tagline', models.CharField(default='दैनिक समाचार पत्र / Daily Newspaper', max_length=255, verbose_name='टैगलाइन / Tagline')),
                ('registration_no', models.CharField(blank=True, default='', max_length=100, verbose_name='पंजीकरण संख्या / RNI Reg. No.')),
                ('bank_name', models.CharField(default='State Bank of India', max_length=150, verbose_name='बैंक का नाम / Bank Name')),
                ('account_number', models.CharField(default='', max_length=50, verbose_name='खाता संख्या / Account Number')),
                ('ifsc_code', models.CharField(default='', max_length=30, verbose_name='आईएफएससी कोड / IFSC Code')),
                ('account_holder_name', models.CharField(default='Vishwaguru', max_length=150, verbose_name='खाताधारक का नाम / Account Holder Name')),
                ('upi_id', models.CharField(default='', max_length=100, verbose_name='यूपीआई आईडी / UPI ID')),
                ('phone_number', models.CharField(default='', max_length=50, verbose_name='संपर्क फ़ोन / Contact Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ईमेल / Email')),
                ('office_address', models.TextField(default='Indore, Madhya Pradesh', verbose_name='कार्यालय का पता / Office Address')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'भुगतान व पत्रशीर्ष विवरण (Payment & Letterhead Info)',
                'verbose_name_plural': 'भुगतान व पत्रशीर्ष विवरण (Payment & Letterhead Info)',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='बिल क्रमांक / Bill Number')),
                ('client_name', models.CharField(max_length=200, verbose_name='विज्ञापनदाता का नाम / Client Name')),
                ('client_phone', models.CharField(max_length=20, verbose_name='फ़ोन नंबर / Client Phone')),
                ('client_address', models.TextField(blank=True, default='', verbose_name='पता व शहर / Client Address')),
                ('client_gstin', models.CharField(blank=True, default='', max_length=50, verbose_name='पैन / जीएसटी नंबर / GSTIN or PAN')),
                ('placement_type', models.CharField(choices=[('Front Page Full', 'मुख्य पृष्ठ - पूरा पेज (Front Page Full)'), ('Front Page Half', 'मुख्य पृष्ठ - आधा पेज (Front Page Half)'), ('Front Page Quarter', 'मुख्य पृष्ठ - चौथाई / 1/4 (Front Quarter)'), ('Inside Page Full', 'अंदर का पृष्ठ - पूरा पेज (Inside Page Full)'), ('Inside Page Half', 'अंदर का पृष्ठ - आधा पेज (Inside Page Half)'), ('Inside Page Quarter', 'अंदर का पृष्ठ - चौथाई / 1/4 (Inside Quarter)'), ('Back Page Full', 'अंतिम पृष्ठ - पूरा पेज (Back Page Full)'), ('Back Page Half', 'अंतिम पृष्ठ - आधा पेज (Back Page Half)'), ('Back Page Quarter', 'अंतिम पृष्ठ - चौथाई / 1/4 (Back Quarter)'), ('Ear Panel', 'शीर्ष विज्ञापन - ईयर पैनल (Ear Panel)'), ('Custom Size', 'अन्य आकार (Custom Size / Specific Dimensions)')], default='Front Page Full', max_length=50, verbose_name='विज्ञापन स्थान व आकार / Placement Preset')),
                ('custom_size_text', models.CharField(blank=True, default='', max_length=100, verbose_name='विशिष्ट आकार / Custom Size (उदा. 8x12 cm)')),
                ('ad_title', models.CharField(blank=True, default='', max_length=255, verbose_name='विज्ञापन शीर्षक / Ad Title or Description')),
                ('edition_date', models.DateField(default=django.utils.timezone.now, verbose_name='प्रकाशन दिनांक / Edition Date')),
                ('edition_name', models.CharField(choices=[('Indore', 'इंदौर (Indore)'), ('Bhopal', 'भोपाल (Bhopal)'), ('Ujjain', 'उज्जैन (Ujjain)'), ('Gwalior', 'ग्वालियर (Gwalior)'), ('Jabalpur', 'जबलपुर (Jabalpur)'), ('State Combined', 'समस्त संस्करण (All Editions / Combined)'), ('Other', 'अन्य (Other)')], default='Indore', max_length=50, verbose_name='संस्करण / Edition Name')),
                ('epaper_link', models.URLField(blank=True, default='', verbose_name='ई-पेपर लिंक / Epaper Verification URL')),
                ('page_number', models.CharField(blank=True, default='Page 1', max_length=30, verbose_name='पृष्ठ संख्या / Page Number')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='मूल राशि / Base Amount (₹)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='छूट / Discount (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='कुल देय राशि / Net Payable Amount (₹)')),
                ('payment_status', models.CharField(choices=[('Unpaid', 'अदत्त (Unpaid)'), ('Paid', 'पूर्ण भुगतान (Paid)'), ('Partial', 'आंशिक भुगतान (Partial)')], default='Unpaid', max_length=20, verbose_name='भुगतान स्थिति / Payment Status')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='प्राप्त राशि / Amount Paid (₹)')),
                ('payment_method', models.CharField(choices=[('Cash', 'नकद (Cash)'), ('UPI', 'यूपीआई (UPI / QR Code)'), ('Bank Transfer', 'बैंक ट्रांसफर (Bank Transfer / NEFT)'), ('Cheque', 'चेक (Cheque)')], default='UPI', max_length=30, verbose_name='भुगतान माध्यम / Payment Method')),
                ('payment_note', models.CharField(blank=True, default='', max_length=255, verbose_name='भुगतान संदर्भ / UTR or Cheque Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='निर्माण समय / Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='संशोधन समय / Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='बिल निर्माता / Created By')),
            ],
            options={
                'verbose_name': 'विज्ञापन बिल (Bill)',
                'verbose_name_plural': 'विज्ञापन बिल (Bills)',
                'ordering': ['-id'],
            },
        ),
    ]
