# Generated by Django 5.1.15 on 2026-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी (Hindi)'), ('bi', 'Bilingual (हिंदी + English)')], default='en', max_length=5, verbose_name='बिल की भाषा / Bill Language'),
        ),
    ]
