# Generated by Django 5.1.15 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_bill_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bi', 'Bilingual (Hindi + English)')], default='en', max_length=5, verbose_name='बिल की भाषा / Bill Language'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='फ़ोन नंबर / Client Phone'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='edition_name',
            field=models.CharField(choices=[('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Ujjain', 'Ujjain'), ('Gwalior', 'Gwalior'), ('Jabalpur', 'Jabalpur'), ('State Combined', 'All Editions (State Combined)'), ('Other', 'Other')], default='Indore', max_length=50, verbose_name='संस्करण / Edition Name'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI / QR Code'), ('Bank Transfer', 'Bank Transfer / NEFT'), ('Cheque', 'Cheque')], default='UPI', max_length=30, verbose_name='भुगतान माध्यम / Payment Method'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20, verbose_name='भुगतान स्थिति / Payment Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='placement_type',
            field=models.CharField(choices=[('Front Page Full', 'Front Page — Full Page'), ('Front Page Half', 'Front Page — Half Page'), ('Front Page Quarter', 'Front Page — Quarter (1/4)'), ('Inside Page Full', 'Inside Page — Full Page'), ('Inside Page Half', 'Inside Page — Half Page'), ('Inside Page Quarter', 'Inside Page — Quarter (1/4)'), ('Back Page Full', 'Back Page — Full Page'), ('Back Page Half', 'Back Page — Half Page'), ('Back Page Quarter', 'Back Page — Quarter (1/4)'), ('Ear Panel', 'Ear Panel (Top Header)'), ('Custom Size', 'Custom Size / Dimensions')], default='Front Page Full', max_length=50, verbose_name='विज्ञापन स्थान व आकार / Placement Preset'),
        ),
    ]
