# Generated by Django 5.1.15 on 2026-09-23 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_bill_language_alter_bill_client_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='विज्ञापनदाता का नाम / Client Name')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='फ़ोन नंबर / Client Phone')),
                ('address', models.TextField(blank=True, default='', verbose_name='पता व शहर / Client Address')),
                ('gstin', models.CharField(blank=True, default='', max_length=50, verbose_name='पैन / जीएसटी नंबर / GSTIN or PAN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ग्राहक / विज्ञापनदाता (Client)',
                'verbose_name_plural': 'ग्राहक सूची (Clients)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='previous_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='पुराना बकाया / Previous Due (₹)'),
        ),
    ]
